### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by jmervine** [jmervine/dockme#2]
- [x] Linking support.
- [x] `--entrypoint` support.
- [x] Support passed config file argument, possibly requires a refactor.
- [x] Extend test cases.
- [x] Start building a collection of common configurations.
- [ ] Consider removing requirement for locally mounted directory -- my concern with this is it then starts overlapping with `docker-compose` (aka `fig`)

```
```
